### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by Gideonseymour** [PhoenixTeamMC/Phoenix-Ascension#13]
![](http://i.imgur.com/YhZMXIp.png)

![](http://i.imgur.com/AiQMM5r.png)

**Comment by SkeletonPunk** [comment]
Its enderzoo thats causing it

**Comment by Gideonseymour** [comment]
Ender Zoo, eh? I'll report that to them.

**Comment by Gideonseymour** [comment]
Backdating to this version should fix it: http://minecraft.curseforge.com/mc-mods/225247-ender-zoo/files/2230509

As well, it looks like it's being fixed for a newer build, so we can grab that when it comes out.
https://github.com/SleepyTrousers/EnderZoo/issues/81

**Comment by Gideonseymour** [comment]
Well, not that version. That's 1.8 >.>
I guess the next one will do. Hold on.
